### PR TITLE
adds mod helper to math.js (closes #256)

### LINKED ISSUE #256: mod operator
where is the mod operator in math?

### PR DESCRIPTION
**Pull request by brendaniel**
math .mod added

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Hi @brendaniel, thanks for the pr. Could you add some unit tests so we can merge? Thanks!

**Comment by jonschlinkert** [comment]
@brendaniel ping

**Comment by brendaniel** [comment]
@jonschlinkert Where do I add unit tests?
I added it to /test/math.js using the describe and it method, but it was rejected at CI.

**Comment by jonschlinkert** [comment]
before [this section in the unit tests](https://github.com/helpers/handlebars-helpers/blob/master/test/math.js#L49-L54). If you add the test and push it up, we can review and debug or give feedback if it's failing.

**Comment by xymbol** [comment]
@jonschlinkert Need help to close this one?

**Comment by jonschlinkert** [comment]
@xymbol yes that would be great, thanks! I think it just needs to be rebased and have unit tests added. 

Maybe we should rename `mod` to `remainder` since that's more semantic and there is a [proposal to add a real modulo operator](http://wiki.ecmascript.org/doku.php?id=strawman:modulo_operator). thoughts?

**Comment by xymbol** [comment]
@jonschlinkert Thanks for asking. Agree on the name. MDN uses the term "remainder" for the `%` operator which matches many modern languages.

Will rename the helper, add tests and re-submit.

**Comment by jonschlinkert** [comment]
closing since this was addressed in the linked commits

**Pull request closed without merging**
