### PR TITLE
0.8.1

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@jonschlinkert @doowb any objections?

**Comment by jonschlinkert** [comment]
Can you get away with just bumping `bower.json` to `0.8.0`? other than that, seems fine to me

**Comment by LaurentGoderre** [comment]
@jonschlinkert no because I am trying to release a new commit since 0.8.0

**Comment by jonschlinkert** [comment]
> I am trying to release a new commit since 0.8.0

Why? Sorry if I'm missing something obvious, but bower.json has nothing to do with npm. publishing a new version on npm won't effect bower in any way (and bower.json won't get published to npm), and bower doesn't look at npm or package.json. Bower only looks at github

**Comment by LaurentGoderre** [comment]
I need that new commit in grunt-assemble so I need a new npm version

**Comment by doowb** [comment]
> I need that new commit in grunt-assemble so I need a new npm version

Can you explain this a little more? Which new commit are you referring to? `handlebars-helpers@0.8.0` is already used in `assemble-handlebars@0.4.1` and that's already used in the latest `grunt-assemble@0.6.3`. Making a change in `bower.json` shouldn't have any affect on those modules.

**Comment by LaurentGoderre** [comment]
I need this commit in a release 0ad46f8dcb12ffb65c66795f5632aefa3c80c3e2

**Comment by doowb** [comment]
That makes more sense now, sorry I didn't notice the other commits. We need to also run verb so the readme is updated (there was another change that added a new helper and will change some of the links).

There are also some other PRs that might be able to go into a patch version. I'll take a look at those today and see if we can include any of them. Then since bumping the version is part of what we do when releasing, I can just do it at that time. Thanks for pointing it out though.

**Comment by jonschlinkert** [comment]
yeah makes more sense now, thanks for the detail. 

> There are also some other PRs that might be able to go into a patch version.

awesome, thanks @doowb!

**Comment by doowb** [comment]
@LaurentGoderre merged and published. You should be able to pull down the latest `grunt-assemble` and it'll handlebars-helpers 0.8.1.

**Pull request merged**
