### PR TITLE
add `.lengthGt`, `.lengthLt`, `.lengthGte` and `.lengthLte` array helper.

### PR DESCRIPTION
**Pull request by why2pac**
Add `.lengthGt`, `.lengthLt`, `.lengthGte` and `.lengthLte` array helper.
Also implement unit tests.

### CODE REVIEW

**Comment by doowb** [comment]
Thanks @why2pac for the PR, but I don't think these are necessary. You can use subexpressions for these:

```handlebars
{{#gt (length array) 2}}more than 2{{else}}less than or equal to 2{{/gt}}
{{#lt (length array) 2}}less than 2{{else}}more than or equal to 2{{/lt}}
{{#gte (length array) 2}}more than or equal to 2{{else}}less than 2{{/gte}}
{{#lte (length array) 2}}less than or equal to 2{{else}}more than 2{{/lte}}
```

Also, subexpressions provide more power, because you can use the `length` helper for both arguments to `gt,lt,gte,lte`:

```handlebars
{{#gt (length array1) (length array2)}}array 1 is greater than array 2{{/gt}}
```

**Comment by why2pac** [comment]
@doowb  Yes. I agree with that. But, I added that helpers to be consistent with `.lengthEqual` helper.

**Comment by jonschlinkert** [comment]
since these can be accomplished as subexpressions, I'm going to go ahead and close. But we do appreciate the pr.  @why2pac to your point about `.lengthEqual` I think that should be removed in a future release for the same reason.

**Comment by why2pac** [comment]
@jonschlinkert OK. I fully understood your point. 👍

**Pull request closed without merging**
