### PR TITLE
Update READ.me

### PR DESCRIPTION
**Pull request by bc-traciporter**
See [DEVDOCS-2990](https://jira.bigcommerce.com/browse/DEVDOCS-2990) for explanation and verification.

### CODE REVIEW

**Review by bc-jz — APPROVED** [review]
Makes sense to me.

**Review by jmwiese — APPROVED** [review]

**Comment by bc-traciporter** [comment]
@jmwiese thank you. Can you merge the changes as well?

**Comment by doowb** [comment]
Hi @traci707 , did you intend to open this PR in another system? The link you provided points to a private jira system.

**Comment by bc-traciporter** [comment]
@doowb  Yes, this is the link that I was told to update. Our dev docs contain a link to this documentation.

**Comment by doowb** [comment]
I'm not able to see the explanation and verification, so I'm not sure what you're fixing here.

This update shows using `JSONparse` as a block helper, which is incorrect because `JSONparse` isn't implemented to handle that.

btw... it looks like you just closed this while I was typing

**Comment by bc-traciporter** [comment]
Yes, closing PR. 
Your documentation is correct for your repo. Sorry for the issue.

**Pull request closed without merging**
